### ISSUE TITLE
Is TransactionUtilitiesKt removed from token sdk ?

### ISSUE THREAD

**Issue by yashbhavsar007** [corda/token-sdk#159]
I have received all the dependencies related to token-sdk and here I am attaching image for same
![Screenshot 2019-11-27 at 3 52 28 PM](https://user-images.githubusercontent.com/26292780/69715269-fdf34300-112d-11ea-9775-832017ba6568.png)

**What I want to do?**
I want to import com.r3.corda.lib.tokens.contracts.utilities.TransactionUtilities for below code 
`        val fungibleToken = FungibleToken(amount,holder,TransactionUtilitiesKt.getAttachmentIdForGenericParam(tokenPointer))`

**Note: I'm doing code in kotlin**

**What happened ?**
It says unresolved reference at TransactionUtilities So, The TransactionUtilities removed in the latest updates? if yes suggest any way to call FungibleToken.

Any suggestions/help appreciated.

**Comment by kasiastreich** [comment]
Hi, function that you are trying to use is an extension function on TokenType: `fun TokenType.getAttachmentIdForGenericParam(): SecureHash?`. So to use it from kotlin you would call it this way: `amount.token.tokenType.getAttachmentIdForGenericParam()` (TransactionUtilitiesKt.etc is Java syntax for calling extension functions). However you don't have to use it at all, as there is a reasonable default for `FungibleToken` constructor. Hope that helps!
If the imports don't work, try to clean caches, there was no change to TransactionUtilities since 1.0

**Comment by yashbhavsar007** [comment]
Yes this one worked for me! Thank you for your help!
